export { default as Achievement } from "./Achievement";
export { default as Companies } from "./Companies";
export { default as Header } from "./Header";
export { default as HowItWorks } from "./HowItWorks";
export { default as ReadyToStart } from "./ReadyToStart";
export { default as Services } from "./Services";
export { default as SmarterWay } from "./SmarterWay";
export { default as Team } from "./Team";
export { default as Testinominals } from "./Testinominals";
